# Basic dependabot.yml file with
# minimum configuration for npm package managers

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `yarn.lock` files in the `root` directory
    directory: '/'
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: 'swiper'
        # For Swiper, ignore all updates for version 5 and 6
        versions: ['5.x', '6.x', '7.x']
