# Basic dependabot.yml file with
# minimum configuration for yarn package managers

version: 1
updates:
  # Enable version updates for yarn
  - package-ecosystem: "yarn"
    # Look for `yarn.lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"